version: '3.8'
services:
  storage_db:
    image: postgres:latest
    container_name: storage_container
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - storage_data:/var/lib/postgresql/data

volumes:
  storage_data:
